### ISSUE TITLE
githash.py - TypeError: can't concat bytes to str

### ISSUE THREAD

**Issue by A-312** [chris3torek/scripts#1]
```
λ python githash.py zds-site
Traceback (most recent call last):
  File "githash.py", line 209, in <module>
    sys.exit(main())
  File "githash.py", line 195, in main
    hasher = generic_hash(path, mode, size, args)
  File "githash.py", line 169, in generic_hash
    hasher = tree_hash(path, args)
  File "githash.py", line 138, in tree_hash
    pass1.sort(key = lambda i: i[4] + '/' if i[1] == '40000' else i[4])
  File "githash.py", line 138, in <lambda>
    pass1.sort(key = lambda i: i[4] + '/' if i[1] == '40000' else i[4])
TypeError: can't concat str to bytes
```

Fix : `.encode('ascii')`

     pass1.sort(key = lambda i: i[4] + '/'.encode('ascii') if i[1] == '40000' else i[4])

> Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32

**Comment by chris3torek** [comment]
Oops, yes.  Simpler fix is to use `b'/'` here—`i[4]` is a `bytes` and `b'...'` works in Python 2.7 these days too.
